/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.auroClin.visao;

import Controler.ValidarCampos;
import DAO.ConsultaDAO;
import DAO.FuncaoSistemaDAO;
import br.auroClin.model.Cidades;
import br.auroClin.model.Consulta;
import br.auroClin.model.Especializacoes;
import java.awt.Dimension;
import java.awt.Font;
import java.text.DecimalFormat;
import java.text.NumberFormat;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;
import javax.swing.text.DefaultFormatterFactory;
import javax.swing.text.NumberFormatter;

/**
 *
 * @author Franciosney Souza
 */
public class CadastroExtra extends javax.swing.JFrame {

    /**
     * Creates new form CadastroExtra
     */
    
    
      public void listarCidade(){
    
        try {
            
              FuncaoSistemaDAO daocos = new FuncaoSistemaDAO();
            List<Cidades> listaConsulta = daocos.listarCidades();
            
            DefaultTableModel modelo = (DefaultTableModel)jTableCidades.getModel();
            modelo.setNumRows(0);
            
            int i = 0;
            for(Cidades cons: listaConsulta){
modelo.addRow(new String[i]);
jTableCidades.setValueAt(cons.getId_cidade(), i, 0);
jTableCidades.setValueAt(cons.getNomeCidade(), i, 1);

            i++;
            }
            
        } catch (Exception e) {}
        }
    
    
    
      
      public void listarEspecializacao(){
    
        try {
            
              FuncaoSistemaDAO daocos = new FuncaoSistemaDAO();
            List<Especializacoes> listaConsulta = daocos.listarEspecializacao();
            
            DefaultTableModel modelo = (DefaultTableModel)jTableEspecializacao.getModel();
            modelo.setNumRows(0);
            
            int i = 0;
            for(Especializacoes cons: listaConsulta){
modelo.addRow(new String[i]);
jTableEspecializacao.setValueAt(cons.getId_especializacao(), i, 0);
jTableEspecializacao.setValueAt(cons.getEspecializacao(), i, 1);

            i++;
            }
            
        } catch (Exception e) {}
        }
    
      
      
    public CadastroExtra() {
        initComponents();
        
        
        
jTextFieldEstado.setDocument(new ValidarCampos());
      jTextFieldCidade.setDocument(new ValidarCampos());
      jTextField1.setDocument(new ValidarCampos());
        
        
           JTableHeader header = jTableCidades.getTableHeader();   
    header.setPreferredSize(new Dimension(0, 50)); 

    	header.setFont(new Font("��������", Font.PLAIN, 14));
	header.setPreferredSize(new Dimension(header.getWidth(),40));
    

        
         jTableCidades.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
jTableCidades.getColumnModel().getColumn(0).setPreferredWidth(80);
jTableCidades.getColumnModel().getColumn(1).setPreferredWidth(435);
jTableCidades.setRowHeight(35); 



           JTableHeader headerr = jTableEspecializacao.getTableHeader();   
    header.setPreferredSize(new Dimension(0, 50)); 

    	headerr.setFont(new Font("��������", Font.PLAIN, 14));
	headerr.setPreferredSize(new Dimension(headerr.getWidth(),40));
    

        
         jTableEspecializacao.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
jTableEspecializacao.getColumnModel().getColumn(0).setPreferredWidth(80);
jTableEspecializacao.getColumnModel().getColumn(1).setPreferredWidth(450);
jTableEspecializacao.setRowHeight(35); 

         
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTableEspecializacao = new javax.swing.JTable();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableCidades = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldEstado = new javax.swing.JTextField();
        jTextFieldCidade = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jButtonFechar4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });
        getContentPane().setLayout(null);

        jTableEspecializacao.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Id", "Especialização"
            }
        ));
        jScrollPane1.setViewportView(jTableEspecializacao);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(30, 150, 540, 140);
        getContentPane().add(jTextField1);
        jTextField1.setBounds(30, 90, 370, 50);

        jButton1.setText("Cadastrar ");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(410, 90, 160, 50);

        jButton2.setText("Cadastrar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(410, 370, 160, 50);

        jTableCidades.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTableCidades.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Id", "Cidade"
            }
        ));
        jScrollPane2.setViewportView(jTableCidades);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(30, 430, 540, 150);

        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setText(" EX:  CE");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(330, 350, 60, 14);

        jLabel2.setText("ESPECIALIZAÇÃO:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(140, 70, 120, 14);

        jLabel3.setText("ESTADO");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(280, 350, 50, 14);

        jTextFieldEstado.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldEstadoKeyTyped(evt);
            }
        });
        getContentPane().add(jTextFieldEstado);
        jTextFieldEstado.setBounds(260, 370, 140, 50);
        getContentPane().add(jTextFieldCidade);
        jTextFieldCidade.setBounds(30, 370, 220, 50);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 30)); // NOI18N
        jLabel4.setText("        Cadastrar Cidade no Sistema");
        jLabel4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(jLabel4);
        jLabel4.setBounds(30, 300, 540, 41);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 30)); // NOI18N
        jLabel5.setText("  Cadastrar Especialização Médica");
        jLabel5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(jLabel5);
        jLabel5.setBounds(70, 20, 460, 41);

        jLabel6.setText("CIDADE:");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(70, 350, 100, 14);

        jButtonFechar4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/auroClin/imagens/Minimizar (2).png"))); // NOI18N
        jButtonFechar4.setToolTipText("Fechar");
        jButtonFechar4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFechar4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonFechar4);
        jButtonFechar4.setBounds(540, 0, 60, 39);

        setSize(new java.awt.Dimension(600, 598));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        
         String cidade = jTextFieldCidade.getText();
         String estado = jTextFieldEstado.getText();
        
         String traco = " - ";
         
         String fina = cidade+traco+estado;
          FuncaoSistemaDAO daof = new FuncaoSistemaDAO();
         
      
        if (jTextFieldCidade.getText().equals("")) {
            
            JOptionPane.showMessageDialog(rootPane, "Adicione uma Cidade!");
            
            
        } else if(jTextFieldEstado.getText().equals("")){
        
        
         JOptionPane.showMessageDialog(rootPane, "Adicione um Estado!");
        
        }else{
        
        
        
        if (daof.validarCidade(fina)) {
            
JOptionPane.showMessageDialog(rootPane, "Cidade Existente no Sistema!");
            
        }else{
        
        daof.cadastrarCidade(fina);
        JOptionPane.showMessageDialog(rootPane, "Cidade Cadastrada Com Sucesso");
        
        }

        
        
        
        }
        
        
        
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
        
        listarCidade();
        listarEspecializacao();
    }//GEN-LAST:event_formWindowActivated

    private void jTextFieldEstadoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldEstadoKeyTyped
        // TODO add your handling code here:
        
        
        int numeroCaracteres = 2;
        if (jTextFieldEstado.getText().length() >= numeroCaracteres) {
            evt.consume();
            JOptionPane.showMessageDialog(rootPane, "Por Favor, Abrevie o Nome do Estado para 2 Digitos, Obrigado!");
        } 
        
        
    }//GEN-LAST:event_jTextFieldEstadoKeyTyped

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        
          String especializacao = jTextField1.getText();

         

          FuncaoSistemaDAO daof = new FuncaoSistemaDAO();
         
      
        if (jTextField1.getText().equals("")) {
            
            JOptionPane.showMessageDialog(rootPane, "Adicione uma Especialização!");
            
            
        }else{
        
        
        
        if (daof.validarEspecializacao(especializacao)) {
            
JOptionPane.showMessageDialog(rootPane, "Especialização Existente no Sistema!");
            
        }else{
        
        daof.cadastrareEspecializacao(especializacao);
        JOptionPane.showMessageDialog(rootPane, "Especialização Cadastrada Com Sucesso");
        
        }

        
        
        
        }
        
        
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButtonFechar4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFechar4ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButtonFechar4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroExtra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroExtra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroExtra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroExtra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastroExtra().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButtonFechar4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTableCidades;
    private javax.swing.JTable jTableEspecializacao;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextFieldCidade;
    private javax.swing.JTextField jTextFieldEstado;
    // End of variables declaration//GEN-END:variables
}
