/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.auroClin.visao;

import Controler.ValidarCampos;
import DAO.ExameDAO;
import DAO.planosDAO;
import br.auroClin.model.Exame;
import br.auroClin.model.planoMODELO;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Font;
import java.text.DecimalFormat;
import java.text.NumberFormat;
import java.text.ParseException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;
import javax.swing.text.DefaultFormatterFactory;
import javax.swing.text.NumberFormatter;

/**
 *
 * @author Franciosney Souza
 */
public class planoAuroClin extends javax.swing.JFrame {

    /**
     * Creates new form planoAuroClin
     */
    
    
    public void listarPlanos(){
    
        try {
            
            planosDAO objpd = new planosDAO();
            List<planoMODELO> listaplanos = objpd.listarPlanos();
            
            DefaultTableModel modelo = (DefaultTableModel)jTablePlanos.getModel();
            modelo.setNumRows(0);
            
    


            int i = 0;
            for(planoMODELO ex: listaplanos){
modelo.addRow(new String[i]);
jTablePlanos.setValueAt(ex.getId_plano(), i, 0);
jTablePlanos.setValueAt(ex.getNomePlano(), i, 1);
jTablePlanos.setValueAt(String.format("%-4s %%", ex.getDesconto()), i, 2);
            i++;
            }
            
        } catch (Exception e) {}
        }
    
    
    
    
    public planoAuroClin() {
        initComponents();
        
      


 DecimalFormat decimal = new DecimalFormat("#,###,###.0");
         NumberFormatter numFormatter = new NumberFormatter(decimal);
         numFormatter.setFormat(decimal);
         numFormatter.setAllowsInvalid(false);
         DefaultFormatterFactory dfFactory = new DefaultFormatterFactory(numFormatter);
         jFormattedTextFieldPrecoDesconto.setFormatterFactory(dfFactory);
         jFormattedTextFieldPrecoDescontoEditar.setFormatterFactory(dfFactory);
        
        
           JTableHeader header = jTablePlanos.getTableHeader();   
    header.setPreferredSize(new Dimension(0, 50)); 

    	header.setFont(new Font("��������", Font.PLAIN, 14));
	header.setPreferredSize(new Dimension(header.getWidth(),40));
    

        
         jTablePlanos.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
jTablePlanos.getColumnModel().getColumn(0).setPreferredWidth(80);
jTablePlanos.getColumnModel().getColumn(1).setPreferredWidth(482);
jTablePlanos.getColumnModel().getColumn(2).setPreferredWidth(100);
jTablePlanos.setRowHeight(35); 



         jTextFieldNomePlano.setDocument(new ValidarCampos());
         jTextFieldNomePlanoEditar.setDocument(new ValidarCampos());
         
         
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jTextFieldNomePlano = new javax.swing.JTextField();
        jFormattedTextFieldPrecoDesconto = new javax.swing.JFormattedTextField();
        jLabel20 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel21 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTablePlanos = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jButtonFechar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jFormattedTextFieldPrecoDescontoEditar = new javax.swing.JFormattedTextField();
        jTextFieldNomePlanoEditar = new javax.swing.JTextField();
        jTextFieldIdEditar = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Categoria");

        jTextFieldNomePlano.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextFieldNomePlano.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextFieldNomePlanoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldNomePlanoFocusLost(evt);
            }
        });
        jTextFieldNomePlano.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNomePlanoActionPerformed(evt);
            }
        });
        jTextFieldNomePlano.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldNomePlanoKeyTyped(evt);
            }
        });

        jFormattedTextFieldPrecoDesconto.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter()));
        jFormattedTextFieldPrecoDesconto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFormattedTextFieldPrecoDescontoActionPerformed(evt);
            }
        });
        jFormattedTextFieldPrecoDesconto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jFormattedTextFieldPrecoDescontoKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jFormattedTextFieldPrecoDescontoKeyTyped(evt);
            }
        });

        jLabel20.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel20.setText("Desconto  x%");

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/auroClin/imagens/salvarB.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel21.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel21.setText("Salvar");

        jTablePlanos.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jTablePlanos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "id", "Categoria", "Desconto"
            }
        ));
        jTablePlanos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTablePlanosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTablePlanos);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(114, 114, 114)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel20)
                        .addGap(102, 102, 102)
                        .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jTextFieldNomePlano, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jFormattedTextFieldPrecoDesconto, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 186, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(jLabel21)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jFormattedTextFieldPrecoDesconto)
                    .addComponent(jTextFieldNomePlano, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 242, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(60, 60, 680, 360);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 30)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("              PLANOS");
        jLabel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(jLabel2);
        jLabel2.setBounds(230, 10, 380, 40);

        jButtonFechar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/auroClin/imagens/Minimizar (2).png"))); // NOI18N
        jButtonFechar.setToolTipText("Fechar");
        jButtonFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFecharActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonFechar);
        jButtonFechar.setBounds(750, 0, 50, 40);

        jButton2.setText("Editar Plano");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jFormattedTextFieldPrecoDescontoEditar.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter()));
        jFormattedTextFieldPrecoDescontoEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFormattedTextFieldPrecoDescontoEditarActionPerformed(evt);
            }
        });
        jFormattedTextFieldPrecoDescontoEditar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jFormattedTextFieldPrecoDescontoEditarKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jFormattedTextFieldPrecoDescontoEditarKeyTyped(evt);
            }
        });

        jTextFieldNomePlanoEditar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextFieldNomePlanoEditar.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextFieldNomePlanoEditarFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldNomePlanoEditarFocusLost(evt);
            }
        });
        jTextFieldNomePlanoEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNomePlanoEditarActionPerformed(evt);
            }
        });
        jTextFieldNomePlanoEditar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldNomePlanoEditarKeyTyped(evt);
            }
        });

        jLabel3.setText("ID");

        jLabel22.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel22.setText("Desconto  x%");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Categoria");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jTextFieldIdEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextFieldNomePlanoEditar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jFormattedTextFieldPrecoDescontoEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel3)
                .addGap(174, 174, 174)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 216, Short.MAX_VALUE)
                .addComponent(jLabel22)
                .addGap(98, 98, 98))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(12, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel22)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextFieldNomePlanoEditar, javax.swing.GroupLayout.DEFAULT_SIZE, 54, Short.MAX_VALUE)
                        .addComponent(jFormattedTextFieldPrecoDescontoEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jTextFieldIdEditar, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, 52, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(jPanel2);
        jPanel2.setBounds(60, 430, 680, 160);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/auroClin/imagens/FundoPlano.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        jLabel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(jLabel1);
        jLabel1.setBounds(30, -40, 770, 710);

        setSize(new java.awt.Dimension(800, 600));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldNomePlanoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldNomePlanoFocusGained
        // TODO add your handling code here:

    }//GEN-LAST:event_jTextFieldNomePlanoFocusGained

    private void jTextFieldNomePlanoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldNomePlanoFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNomePlanoFocusLost

    private void jTextFieldNomePlanoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNomePlanoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNomePlanoActionPerformed

    private void jTextFieldNomePlanoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldNomePlanoKeyTyped
        // TODO add your handling code here:

        int numeroCaracteres = 20;
        if (jTextFieldNomePlano.getText().length() > numeroCaracteres) {
            evt.consume();
            JOptionPane.showMessageDialog(rootPane, "Texto muito grande! Abrevie Algumas Palavras");
        }
    }//GEN-LAST:event_jTextFieldNomePlanoKeyTyped

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        if (jTextFieldNomePlano.getText().equals("")) {
            
            JOptionPane.showMessageDialog(rootPane, "Digite um categoria para o desconto");
            jTextFieldNomePlano.setBackground(new java.awt.Color(255, 102, 102));
            
        }else if(jFormattedTextFieldPrecoDesconto.getText().equals("")){
        
             JOptionPane.showMessageDialog(rootPane, "Campo Obrigatório! Digite um valor em Porcentagem de 0 a 100");
            jFormattedTextFieldPrecoDesconto.setBackground(new java.awt.Color(255, 102, 102));
        
        } else{
        
        
            try {
            
            
             float valor = NumberFormat.getInstance().parse(jFormattedTextFieldPrecoDesconto.getText()).floatValue();
           
            
           float valorLimite = 100;
           
           if (valor > valorLimite) {
        
             JOptionPane.showMessageDialog(rootPane, "Digite um valor em Porcentagem de 0 a 100, Obrigado");
             
               
               
    } else{
           
                  int dialogButton = JOptionPane.YES_NO_OPTION;
   int dialogResult = JOptionPane.showConfirmDialog (null, "Você tem Certeza que Deseja Cadastrar um Novo Plano?","Warning",dialogButton);
if(dialogResult == JOptionPane.YES_OPTION){
    
    
    planosDAO daop = new planosDAO();
    
    String planoNome = jTextFieldNomePlano.getText();
    
    if (daop.validarplano(planoNome)) {
        
          JOptionPane.showMessageDialog(rootPane, "Esse plano ja esta cadastrado, Obrigado!");
        
    }else{
    
      planoMODELO obj = new planoMODELO();
                
                
            obj.setNomePlano(jTextFieldNomePlano.getText());
             float preco = NumberFormat.getInstance().parse(jFormattedTextFieldPrecoDesconto.getText()).floatValue();
            obj.setDesconto(preco);
           
               
       
               
               daop.cadastrarPlano(obj);
               JOptionPane.showMessageDialog(rootPane, "Categoria Cadastrada Com Sucesso");



    
    }

    
     
}else{

 JOptionPane.showMessageDialog(rootPane, "Você Não Cadastrou o Plano!");

}

               
               
               
             
               
           
           }
            
            
            
            
            
        } catch (Exception e) {
        }
        
            
        
        
        }
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:

        listarPlanos();
    }//GEN-LAST:event_formWindowActivated

    private void jFormattedTextFieldPrecoDescontoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jFormattedTextFieldPrecoDescontoKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_jFormattedTextFieldPrecoDescontoKeyTyped

    private void jFormattedTextFieldPrecoDescontoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jFormattedTextFieldPrecoDescontoKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFormattedTextFieldPrecoDescontoKeyPressed

    private void jFormattedTextFieldPrecoDescontoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFormattedTextFieldPrecoDescontoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFormattedTextFieldPrecoDescontoActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        
        if (jTextFieldIdEditar.getText().equals("")) {
             JOptionPane.showMessageDialog(rootPane, "Selecione um Plano na Tabela, Obrigado!");
            
        }else if(jFormattedTextFieldPrecoDescontoEditar.getText().equals("")){
        
        
         JOptionPane.showMessageDialog(rootPane, "Informe um Valor em Porcentagem, Obrigado!");
         jFormattedTextFieldPrecoDescontoEditar.setBackground(Color.red);
        
        
        }else{
            
            
            
            try {
                float valor = NumberFormat.getInstance().parse(jFormattedTextFieldPrecoDescontoEditar.getText()).floatValue();
                
                
                float valorLimite = 100;
                if (valor > valorLimite) {
                    
                    JOptionPane.showMessageDialog(rootPane, "Digite um valor em Porcentagem de 0 a 100, Obrigado");
                    
                    
                    
                }else{
                    
                  
                    
                    
                     
                
                int dialogButton = JOptionPane.YES_NO_OPTION;
                int dialogResult = JOptionPane.showConfirmDialog (null, "Você tem Certeza que Deseja Editar Esse Plano?","Warning",dialogButton);
                if(dialogResult == JOptionPane.YES_OPTION){
                    
                    
                    
                    
                    
                    
                    try {
                        int idPlanoEditar = Integer.parseInt(jTextFieldIdEditar.getText());
                        String nomePlanoEditar = jTextFieldNomePlanoEditar.getText();
                        
                        float valorDescontoEditar = NumberFormat.getInstance().parse(jFormattedTextFieldPrecoDescontoEditar.getText()).floatValue();
                        planosDAO daop = new planosDAO();
                        daop.editarPlanos(nomePlanoEditar, valorDescontoEditar, idPlanoEditar);
                        daop.editarPlanosEmPacientes(nomePlanoEditar, idPlanoEditar);
                        JOptionPane.showMessageDialog(rootPane, "Categoria Editada Com Sucesso!");
                        jTextFieldIdEditar.setText("");
                        jTextFieldNomePlanoEditar.setText("");
                        jFormattedTextFieldPrecoDescontoEditar.setValue(null);
                        
                    } catch (ParseException ex) {
                        Logger.getLogger(planoAuroClin.class.getName()).log(Level.SEVERE, null, ex);
                    }
                    
                    
                    
                    
                    /*planoMODELO modp = new planoMODELO();
                    modp.setId_plano(Integer.parseInt(jTextFieldExcluir.getText()));
                    daop.excluirPlano(modp);
                    JOptionPane.showMessageDialog(rootPane, "Plano Excuido Com Sucesso");
                    */
                    
                }else{
                    
                    
                    JOptionPane.showMessageDialog(rootPane, "Você Não Editou Esta Categória!");
                    
                }     
                    
                    
                    
                    
                }
                
                
                
                
                
                
                
                
                
                
                
                
                     } catch (ParseException ex) {
                Logger.getLogger(planoAuroClin.class.getName()).log(Level.SEVERE, null, ex);
            }
        
        
            
            
            
        }
        
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTablePlanosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTablePlanosMouseClicked
        // TODO add your handling code here:
        
        jTextFieldIdEditar.setText(jTablePlanos.getValueAt(jTablePlanos.getSelectedRow(), 0).toString());
         jTextFieldNomePlanoEditar.setText(jTablePlanos.getValueAt(jTablePlanos.getSelectedRow(), 1).toString());
          jFormattedTextFieldPrecoDescontoEditar.setBackground(new java.awt.Color(0, 255, 204));
          
          
        
    }//GEN-LAST:event_jTablePlanosMouseClicked

    private void jButtonFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFecharActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButtonFecharActionPerformed

    private void jFormattedTextFieldPrecoDescontoEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFormattedTextFieldPrecoDescontoEditarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFormattedTextFieldPrecoDescontoEditarActionPerformed

    private void jFormattedTextFieldPrecoDescontoEditarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jFormattedTextFieldPrecoDescontoEditarKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFormattedTextFieldPrecoDescontoEditarKeyPressed

    private void jFormattedTextFieldPrecoDescontoEditarKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jFormattedTextFieldPrecoDescontoEditarKeyTyped
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jFormattedTextFieldPrecoDescontoEditarKeyTyped

    private void jTextFieldNomePlanoEditarFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldNomePlanoEditarFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNomePlanoEditarFocusGained

    private void jTextFieldNomePlanoEditarFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldNomePlanoEditarFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNomePlanoEditarFocusLost

    private void jTextFieldNomePlanoEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNomePlanoEditarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNomePlanoEditarActionPerformed

    private void jTextFieldNomePlanoEditarKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldNomePlanoEditarKeyTyped
        // TODO add your handling code here:
        
         int numeroCaracteres = 20;
        if (jTextFieldNomePlanoEditar.getText().length() > numeroCaracteres) {
            evt.consume();
            JOptionPane.showMessageDialog(rootPane, "Texto muito grande! Abrevie Algumas Palavras");
        }
    }//GEN-LAST:event_jTextFieldNomePlanoEditarKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(planoAuroClin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(planoAuroClin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(planoAuroClin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(planoAuroClin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new planoAuroClin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButtonFechar;
    private javax.swing.JFormattedTextField jFormattedTextFieldPrecoDesconto;
    private javax.swing.JFormattedTextField jFormattedTextFieldPrecoDescontoEditar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTablePlanos;
    private javax.swing.JTextField jTextFieldIdEditar;
    private javax.swing.JTextField jTextFieldNomePlano;
    private javax.swing.JTextField jTextFieldNomePlanoEditar;
    // End of variables declaration//GEN-END:variables
}
