/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.auroClin.visao;

import br.auroClin.model.ControleLog;
import br.auroClin.model.IreporterReceituarios;
import br.auroClin.model.imprimirComprovanteModelo;
import java.awt.Font;
import java.awt.Insets;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import javax.swing.JOptionPane;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.data.JRBeanCollectionDataSource;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author Franciosney Souza
 */
public class receituarioNormal extends javax.swing.JFrame {

    /**
     * Creates new form receituarioNormal
     * @param idServico
     * @param paciente
     * @param data
     * @param servico
     */
    
    
    
    
    public void receber(int idServico,String paciente,String servico,String data){
       jTextFieldIdServico.setText(Integer.toString(idServico));
       jTextFieldPaciente.setText(paciente);
       jTextFieldServico.setText(servico);
       jTextFieldData.setText(data);
       
      
       

   
    
    }
    
    
    
    
    public receituarioNormal() {
        initComponents();
        
        
        
    
       jTextFieldIdServico.setEditable(false);
       jTextFieldIdServico.setBackground(new java.awt.Color(204, 204, 255));
       jTextFieldPaciente.setEditable(false);
       jTextFieldPaciente.setBackground(new java.awt.Color(204, 204, 255));
       jTextFieldServico.setEditable(false);
       jTextFieldServico.setBackground(new java.awt.Color(204, 204, 255));
       jTextFieldData.setEditable(false);      
       jTextFieldData.setBackground(new java.awt.Color(204, 204, 255));
       jTextFieldMedico.setEditable(false);      
       jTextFieldMedico.setBackground(new java.awt.Color(204, 204, 255));
        
        
       
     
                jTextAreaReceituario.setFont(new Font("Monospaced", 0, 20));
                jTextAreaReceituario.setLineWrap(true);
                jTextAreaReceituario.setMargin(new Insets(10, 10, 10, 10));
       
       jTextFieldMedico.setText("Dr. "+ControleLog.getNomeMedico());
       
       
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jButtonFechar1 = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTextAreaReceituario = new javax.swing.JTextArea();
        jTextFieldData = new javax.swing.JTextField();
        jTextFieldIdServico = new javax.swing.JTextField();
        jTextFieldMedico = new javax.swing.JTextField();
        jTextFieldServico = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jTextFieldPaciente = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(null);

        jButtonFechar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/auroClin/imagens/Minimizar (2).png"))); // NOI18N
        jButtonFechar1.setToolTipText("Fechar");
        jButtonFechar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFechar1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonFechar1);
        jButtonFechar1.setBounds(620, 30, 63, 39);

        jTextAreaReceituario.setColumns(20);
        jTextAreaReceituario.setRows(5);
        jScrollPane4.setViewportView(jTextAreaReceituario);

        jPanel2.add(jScrollPane4);
        jScrollPane4.setBounds(20, 250, 670, 250);
        jPanel2.add(jTextFieldData);
        jTextFieldData.setBounds(560, 210, 130, 30);
        jPanel2.add(jTextFieldIdServico);
        jTextFieldIdServico.setBounds(20, 210, 60, 30);
        jPanel2.add(jTextFieldMedico);
        jTextFieldMedico.setBounds(20, 520, 420, 40);
        jPanel2.add(jTextFieldServico);
        jTextFieldServico.setBounds(390, 210, 160, 30);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/auroClin/imagens/logoAuroClin.png"))); // NOI18N
        jPanel2.add(jLabel2);
        jLabel2.setBounds(140, 40, 440, 100);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 204, 204));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/auroClin/imagens/localizacao.png"))); // NOI18N
        jLabel3.setText("Travessa Antônio Pinto, 200 - Centro - Aurora - CE");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(50, 620, 490, 40);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 204, 204));
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/auroClin/imagens/email.png"))); // NOI18N
        jLabel4.setText("   auroclin@hotmail.com");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(380, 580, 300, 40);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 204, 204));
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/auroClin/imagens/whatsapp.png"))); // NOI18N
        jLabel5.setText(" (88) 99970.3700 / 99411.8286");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(50, 580, 300, 40);

        jButton1.setText("Cadastrar Receituário");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1);
        jButton1.setBounds(450, 520, 240, 40);
        jPanel2.add(jTextFieldPaciente);
        jTextFieldPaciente.setBounds(90, 210, 290, 30);

        jLabel6.setText("Data");
        jPanel2.add(jLabel6);
        jLabel6.setBounds(570, 190, 90, 14);

        jLabel7.setText("Médico Responsável");
        jPanel2.add(jLabel7);
        jLabel7.setBounds(200, 494, 130, 30);

        jLabel8.setText("Paciente");
        jPanel2.add(jLabel8);
        jLabel8.setBounds(120, 190, 140, 14);

        jLabel9.setText("Serviço");
        jPanel2.add(jLabel9);
        jLabel9.setBounds(410, 190, 90, 14);

        jLabel10.setText("Codigo");
        jPanel2.add(jLabel10);
        jLabel10.setBounds(30, 190, 40, 14);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/auroClin/imagens/fundoprontuarioNormal.png"))); // NOI18N
        jPanel2.add(jLabel1);
        jLabel1.setBounds(0, 0, 710, 700);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(712, 700));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonFechar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFechar1ActionPerformed
        // TODO add your handling code here:

        this.dispose();

    }//GEN-LAST:event_jButtonFechar1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        
        
        
          List lista = new ArrayList();
                
             String nome = jTextFieldPaciente.getText();
              String servico = jTextFieldServico.getText();
               String data = jTextFieldData.getText();
               String medico = jTextFieldMedico.getText();
               String receituarioDigitado = jTextAreaReceituario.getText();
          String endereco = null;
             
         
                    IreporterReceituarios receituario = new IreporterReceituarios(nome,servico,data,medico,receituarioDigitado,endereco);
                    lista.add(receituario);
                    
                    
                    try {
                        
                          
                      Map parametros = new HashMap();  

          JasperPrint print = JasperFillManager.fillReport("C:/Users/Franciosney Souza/Documents/NetBeansProjects/auroClin/RelatoriosProntos/reporterProntuarioNormal.jasper", 
                    parametros,new JRBeanCollectionDataSource(lista));
            
            JasperViewer  vj = new JasperViewer(print,false);
            vj.setVisible(true);
    
            
        } catch (Exception e) {
            
                        JOptionPane.showMessageDialog(rootPane, e);
            
        }
                    
                  
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(receituarioNormal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(receituarioNormal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(receituarioNormal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(receituarioNormal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new receituarioNormal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonFechar1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTextArea jTextAreaReceituario;
    private javax.swing.JTextField jTextFieldData;
    private javax.swing.JTextField jTextFieldIdServico;
    private javax.swing.JTextField jTextFieldMedico;
    private javax.swing.JTextField jTextFieldPaciente;
    private javax.swing.JTextField jTextFieldServico;
    // End of variables declaration//GEN-END:variables
}
